export const storeType = ["", "Restaurant", "Cafe", "Fast Food", "Supermarket", "Home Appliances"]
export const sortBy = ["", "Most viewed", "Most rating", "Newest", "Closest to me"]
export const range = ["", "0.5 km", "1 km", "2 km", "5 km", "10 km", "100 km"]
export const location = ["", "Eindhoven", "Amsterdam", "Rotterdam", "The Hague"]
export const travelMode = [ "Driving", "Walking", "Bicycling", "Transit"]
